name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build binary
      run: go build -ldflags "-X node-manager-cli/config.CLIVersion=${{ github.event.release.tag_name }}" -o node-manager-cli

    - name: Archive binary
      run: tar -czvf node-manager-cli.tar.gz node-manager-cli

    - name: Upload release assets
      run: gh release upload "${{ github.event.release.tag_name }}" node-manager-cli node-manager-cli.tar.gz --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
